// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIQcd1mr6rZXEPIxyChaB5h2FWfmql6Vc',
    appId: '1:394012239431:web:6bd747d8f812bf65083362',
    messagingSenderId: '394012239431',
    projectId: 'screen-lock-sample',
    authDomain: 'screen-lock-sample.firebaseapp.com',
    storageBucket: 'screen-lock-sample.appspot.com',
    measurementId: 'G-GHXNB7FDS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKIJqYgM2XOcIFnfOJKy1hYR1WalaHwGg',
    appId: '1:394012239431:android:caec47d71219aa18083362',
    messagingSenderId: '394012239431',
    projectId: 'screen-lock-sample',
    storageBucket: 'screen-lock-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdTm75XasASKJn8sQSwYf7RwmfrPGeM3E',
    appId: '1:394012239431:ios:071b1e25bb1b7709083362',
    messagingSenderId: '394012239431',
    projectId: 'screen-lock-sample',
    storageBucket: 'screen-lock-sample.appspot.com',
    iosBundleId: 'com.example.screenLock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdTm75XasASKJn8sQSwYf7RwmfrPGeM3E',
    appId: '1:394012239431:ios:03b0fd6dd11c0d01083362',
    messagingSenderId: '394012239431',
    projectId: 'screen-lock-sample',
    storageBucket: 'screen-lock-sample.appspot.com',
    iosBundleId: 'com.example.screenLock.RunnerTests',
  );
}
